networks:
  sm-network2:

services:
  smweb:
    build: .
    container_name: sm-drupal-web
    restart: always
    ports:
      - "8083:80"
    networks:
      - sm-network2    
    volumes:
      - ./drupal:/opt/drupal
    environment:
      - DRUPAL_DB_HOST=database
      - DRUPAL_DB_PORT=3306
      - DRUPAL_DB_NAME=drupal11
      - DRUPAL_DB_USER=drupal11
      - DRUPAL_DB_PASSWORD=drupal11
    depends_on:
      - database

  database:
    image: mariadb
    container_name: sm-db
    networks:
      - sm-network2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drupal11
      MYSQL_USER: drupal11
      MYSQL_PASSWORD: drupal11
    volumes:
      - ./mariadb-data:/var/lib/mysql
    restart: always

